version: '3'
services:
  nginx:
    image: alroniks/nginx:latest
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - 3333:80
    restart: unless-stopped
    depends_on:
      - php
      - db
  php:
    build: ./docker/php/
    restart: always
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./src:/var/www/html
  db:
    image: postgres:10.1
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres/:/docker-entrypoint-initdb.d/
